// <auto-generated />
using System;
using Mazaad.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mazaad.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502142943_AddMissingFieldsAndSeeds")]
    partial class AddMissingFieldsAndSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mazaad.Domain.Models.App_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed@siemens-mena.com",
                            FullName = "Ahmed Al-Rashid",
                            IsActive = true,
                            JobTitle = "Asset Manager",
                            LastLoginDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "hashed_password_placeholder"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara@gulhheavy.com",
                            FullName = "Sara Johnson",
                            IsActive = true,
                            JobTitle = "Procurement Officer",
                            LastLoginDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "hashed_password_placeholder"
                        });
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Bids", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BidAmountPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BuyerCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("PlacedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("WinningBid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BuyerCompanyId");

                    b.HasIndex("ListingId");

                    b.HasIndex("PlacedByUserId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Chat_Channels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("SellerCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerCompanyId");

                    b.HasIndex("ListingId");

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("ChatChannels");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Commission_Policies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CommissionPolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CommissionRate = 2.5m,
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxAmount = 10000000m,
                            MinAmount = 10000m,
                            PolicyName = "Standard Platform Fee"
                        });
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommercialRegNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("TaxRegistrationNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetails = "Industrial Park West, Gate 12, Munich 80331, DE",
                            City = "Munich",
                            CommercialRegNum = "CR-001-2025",
                            CompanyName = "Siemens Healthineers MENA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 1,
                            IsVerified = true,
                            TaxRegistrationNum = "TRN-001-2025",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AddressDetails = "Al Quoz Industrial Area 3, Dubai, UAE",
                            City = "Dubai",
                            CommercialRegNum = "CR-002-2025",
                            CompanyName = "Gulf Heavy Equipment LLC",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 2,
                            IsVerified = true,
                            TaxRegistrationNum = "TRN-002-2025",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AddressDetails = "2400 Technology Drive, Austin TX 78745, US",
                            City = "Austin",
                            CommercialRegNum = "CR-003-2025",
                            CompanyName = "Hydro Cooling Solutions",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 3,
                            IsVerified = true,
                            TaxRegistrationNum = "TRN-003-2025",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Mazaad.Domain.Models.IndustryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IndustryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryName = "Medical Devices",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryName = "Heavy Machinery",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryName = "Data Centers",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryName = "Real Estate",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryName = "Robotics",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Listings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("BidCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentHighestBid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DueDiligenceUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("MinOrderQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurityPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 1m,
                            BaseCurrency = "USD",
                            BidCount = 12,
                            CategoryId = 1,
                            CompanyId = 1,
                            Condition = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentHighestBid = 3420000m,
                            Description = "Deutsche Klinik Regional Distribution Center · Condition: Certified/Refurbished. Full-body 3 Tesla MRI system with 70cm bore.",
                            DueDiligenceUrls = "inspection_report.pdf,maintenance_log.pdf,terms_of_sale.pdf",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800",
                            IsDeleted = false,
                            Location = "Industrial Park West, Gate 12, Munich 80331, DE",
                            MinOrderQuantity = 1m,
                            PurityPercentage = 100m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TechnicalSpecs = "{\"FieldStrength\":\"3 Tesla\",\"BoreSize\":\"70 cm\",\"ManufactureDate\":\"October 2021\",\"ImportStatus\":\"Documentation/Cited\",\"SoftwareVersion\":\"Syngo MR E11\"}",
                            Title = "Siemens Healthineers Lumina 3T MRI Suite",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 3m,
                            BaseCurrency = "USD",
                            BidCount = 8,
                            CategoryId = 2,
                            CompanyId = 2,
                            Condition = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentHighestBid = 285000m,
                            Description = "Late 2024 model, 49-tonne hydraulic excavator with advanced automation package.",
                            DueDiligenceUrls = "excavator_inspection.pdf",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
                            IsDeleted = false,
                            Location = "Al Quoz Industrial Area 3, Dubai, UAE",
                            MinOrderQuantity = 1m,
                            PurityPercentage = 100m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TechnicalSpecs = "{\"OperatingWeight\":\"49 tonnes\",\"NetPower\":\"396 HP\",\"MaxDigDepth\":\"7.42m\",\"Condition\":\"New\"}",
                            Title = "Caterpillar 349 Next Gen Hydraulic Excavator",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 2m,
                            BaseCurrency = "USD",
                            BidCount = 5,
                            CategoryId = 3,
                            CompanyId = 3,
                            Condition = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentHighestBid = 1240000m,
                            Description = "128x NVIDIA H100 80GB SXM5 GPUs in liquid-cooled rack cluster configuration.",
                            DueDiligenceUrls = "cluster_specs.pdf,warranty.pdf",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
                            IsDeleted = false,
                            Location = "2400 Technology Drive, Austin TX 78745, US",
                            MinOrderQuantity = 1m,
                            PurityPercentage = 100m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TechnicalSpecs = "{\"GPUs\":\"128x NVIDIA H100 80GB\",\"CoolingType\":\"Liquid\",\"TDP\":\"700W per GPU\",\"Interconnect\":\"NVLink 4.0\"}",
                            Title = "Bulk Liquid-Cooled GPU Cluster (128x H100)",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 10m,
                            BaseCurrency = "USD",
                            BidCount = 3,
                            CategoryId = 4,
                            CompanyId = 2,
                            Condition = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentHighestBid = 640000m,
                            Description = "10x 2026 electric delivery vans, 400km range, pre-configured with fleet management software.",
                            DueDiligenceUrls = "fleet_inspection.pdf",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
                            IsDeleted = false,
                            Location = "Dubai Fleet Depot, Al Quoz, UAE",
                            MinOrderQuantity = 10m,
                            PurityPercentage = 100m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TechnicalSpecs = "{\"Units\":10,\"Range\":\"400 km\",\"Payload\":\"900 kg\",\"Charging\":\"DC Fast 150kW\"}",
                            Title = "2026 EV Delivery Fleet Bundle (10 Units)",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 1m,
                            BaseCurrency = "USD",
                            BidCount = 2,
                            CategoryId = 5,
                            CompanyId = 1,
                            Condition = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentHighestBid = 18500000m,
                            Description = "Grade-A commercial office building, 12 floors, 15,000 sqm GLA, fully tenanted.",
                            DueDiligenceUrls = "property_report.pdf,tenancy_schedule.pdf",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800",
                            IsDeleted = false,
                            Location = "Downtown Business District, Munich, DE",
                            MinOrderQuantity = 1m,
                            PurityPercentage = 100m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TechnicalSpecs = "{\"GLA\":\"15000 sqm\",\"Floors\":12,\"Occupancy\":\"97%\",\"Certification\":\"LEED Gold\"}",
                            Title = "Downtown Financial District Office Complex",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 5m,
                            BaseCurrency = "USD",
                            BidCount = 7,
                            CategoryId = 6,
                            CompanyId = 3,
                            Condition = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentHighestBid = 192500m,
                            Description = "5x FANUC R-2000iC/165F robotic arms, fully integrated production line, 2023 vintage.",
                            DueDiligenceUrls = "robot_certifications.pdf,maintenance_history.pdf",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=800",
                            IsDeleted = false,
                            Location = "2400 Technology Drive, Austin TX 78745, US",
                            MinOrderQuantity = 5m,
                            PurityPercentage = 100m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TechnicalSpecs = "{\"Units\":5,\"Payload\":\"165 kg\",\"Reach\":\"2655 mm\",\"Repeatability\":\"±0.05 mm\",\"Year\":2023}",
                            Title = "FANUC R-2000iC Production Line (5 Units)",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Material_Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Medical Equipment",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diagnostic and therapeutic medical devices",
                            UnitOfMeasure = "Unit"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Construction Machinery",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heavy construction and earthmoving equipment",
                            UnitOfMeasure = "Unit"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "IT Infrastructure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Servers, networking equipment and cooling systems",
                            UnitOfMeasure = "Unit"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Fleet Vehicles",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial and fleet vehicle bundles",
                            UnitOfMeasure = "Fleet"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Real Estate",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial and industrial real estate",
                            UnitOfMeasure = "sqm"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Industrial Robots",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Robotic arms and automated production lines",
                            UnitOfMeasure = "Unit"
                        });
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AgreedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AgreedUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppliedPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("BidId")
                        .HasColumnType("int");

                    b.Property<int>("BuyerCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppliedPolicyId");

                    b.HasIndex("BidId");

                    b.HasIndex("BuyerCompanyId");

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.App_Users", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Companies", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Bids", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Companies", "BuyerCompany")
                        .WithMany("Bids")
                        .HasForeignKey("BuyerCompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Listings", "Listing")
                        .WithMany("Bids")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.App_Users", "User")
                        .WithMany("Bids")
                        .HasForeignKey("PlacedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BuyerCompany");

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Chat_Channels", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Companies", "BuyerCompany")
                        .WithMany("BuyerChatChannels")
                        .HasForeignKey("BuyerCompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Listings", "Listing")
                        .WithMany("Chat_Channels")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Companies", "SellerCompany")
                        .WithMany("SellerChatChannels")
                        .HasForeignKey("SellerCompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BuyerCompany");

                    b.Navigation("Listing");

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Companies", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.IndustryType", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Listings", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Material_Categories", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Companies", "Company")
                        .WithMany("Listings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Messages", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Chat_Channels", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.App_Users", "SenderUser")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Notifications", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.App_Users", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Orders", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Commission_Policies", "AppliedPolicy")
                        .WithMany("AppliedOrders")
                        .HasForeignKey("AppliedPolicyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Bids", "Bid")
                        .WithMany("Orders")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Companies", "BuyerCompany")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("BuyerCompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Companies", "SellerCompany")
                        .WithMany("SalesOrders")
                        .HasForeignKey("SellerCompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppliedPolicy");

                    b.Navigation("Bid");

                    b.Navigation("BuyerCompany");

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Payments", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Orders", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.App_Users", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Bids", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Chat_Channels", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Commission_Policies", b =>
                {
                    b.Navigation("AppliedOrders");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Companies", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("BuyerChatChannels");

                    b.Navigation("Listings");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SalesOrders");

                    b.Navigation("SellerChatChannels");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.IndustryType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Listings", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Chat_Channels");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Material_Categories", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Orders", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
