// <auto-generated />
using System;
using Mazaad.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mazaad.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328043118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mazaad.Domain.Models.App_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_login_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("company_id");

                    b.ToTable("App_Users");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Bids", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("bid_amount_per_unit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("buyer_company_id")
                        .HasColumnType("int");

                    b.Property<int>("listing_id")
                        .HasColumnType("int");

                    b.Property<int>("placed_by_user_id")
                        .HasColumnType("int");

                    b.Property<decimal>("total_bid_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("winning_bid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("buyer_company_id");

                    b.HasIndex("listing_id");

                    b.HasIndex("placed_by_user_id");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Chat_Channels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("buyer_company_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("listing_id")
                        .HasColumnType("int");

                    b.Property<int>("seller_company_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("buyer_company_id");

                    b.HasIndex("listing_id");

                    b.HasIndex("seller_company_id");

                    b.ToTable("Chat_Channels");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Commission_Policies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Commission_Policies");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("address_details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("commercial_reg_num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("industry_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_verified")
                        .HasColumnType("bit");

                    b.Property<string>("tax_registration_num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("industry_id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.IndustryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IndustryTypes");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Listings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("available_quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("company_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("min_order_quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("purity_percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("category_id");

                    b.HasIndex("company_id");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Material_Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_of_measure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Material_Categories");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("channel_id")
                        .HasColumnType("int");

                    b.Property<string>("message_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sender_user_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("sent_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("channel_id");

                    b.HasIndex("sender_user_id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reference_id")
                        .HasColumnType("int");

                    b.Property<string>("reference_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("agreed_quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("agreed_unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("applied_policy_id")
                        .HasColumnType("int");

                    b.Property<int>("bid_id")
                        .HasColumnType("int");

                    b.Property<int>("buyer_company_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("platform_fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("seller_company_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("applied_policy_id");

                    b.HasIndex("bid_id");

                    b.HasIndex("buyer_company_id");

                    b.HasIndex("seller_company_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("paid_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaction_reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("order_id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.App_Users", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Companies", "Company")
                        .WithMany("Users")
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Bids", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Companies", "BuyerCompany")
                        .WithMany("Bids")
                        .HasForeignKey("buyer_company_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Listings", "Listing")
                        .WithMany("Bids")
                        .HasForeignKey("listing_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.App_Users", "User")
                        .WithMany("Bids")
                        .HasForeignKey("placed_by_user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BuyerCompany");

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Chat_Channels", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Companies", "BuyerCompany")
                        .WithMany("BuyerChatChannels")
                        .HasForeignKey("buyer_company_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Listings", "Listing")
                        .WithMany("Chat_Channels")
                        .HasForeignKey("listing_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Companies", "SellerCompany")
                        .WithMany("SellerChatChannels")
                        .HasForeignKey("seller_company_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BuyerCompany");

                    b.Navigation("Listing");

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Companies", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.IndustryType", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("industry_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Listings", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Material_Categories", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Companies", "Company")
                        .WithMany("Listings")
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Messages", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Chat_Channels", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("channel_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.App_Users", "SenderUser")
                        .WithMany("Messages")
                        .HasForeignKey("sender_user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Notifications", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.App_Users", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Orders", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Commission_Policies", "AppliedPolicy")
                        .WithMany("AppliedOrders")
                        .HasForeignKey("applied_policy_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Bids", "Bid")
                        .WithMany("Orders")
                        .HasForeignKey("bid_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Companies", "BuyerCompany")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("buyer_company_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mazaad.Domain.Models.Companies", "SellerCompany")
                        .WithMany("SalesOrders")
                        .HasForeignKey("seller_company_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppliedPolicy");

                    b.Navigation("Bid");

                    b.Navigation("BuyerCompany");

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Payments", b =>
                {
                    b.HasOne("Mazaad.Domain.Models.Orders", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.App_Users", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Bids", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Chat_Channels", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Commission_Policies", b =>
                {
                    b.Navigation("AppliedOrders");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Companies", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("BuyerChatChannels");

                    b.Navigation("Listings");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SalesOrders");

                    b.Navigation("SellerChatChannels");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.IndustryType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Listings", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Chat_Channels");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Material_Categories", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Mazaad.Domain.Models.Orders", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
