<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Application references both Domain and Infrastructure (for AppDbContext) -->
  <ItemGroup>
    <ProjectReference Include="..\Mazaad.Domain\Mazaad.Domain.csproj" />
    <ProjectReference Include="..\Mazaad.Infrastructure\Mazaad.Infrastructure.csproj" />
  </ItemGroup>

</Project>
